--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DATA3
--------------------------------------------------------

  CREATE TABLE "MBC"."DATA3" 
   (	"NUM" NUMBER(6,0), 
	"STATUTE_NAME" VARCHAR2(100 BYTE), 
	"EFFECTIVE_DATE" VARCHAR2(100 BYTE), 
	"PROCLAMATION_DATE" VARCHAR2(100 BYTE), 
	"STATUTE_TYPE" VARCHAR2(100 BYTE), 
	"STATUTE_ABBRV" VARCHAR2(100 BYTE), 
	"STATUTE_CATEGORY" VARCHAR2(100 BYTE), 
	"SENTENCES" CLOB, 
	"DATA_CLASS" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("SENTENCES") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index DATA3_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MBC"."DATA3_PK" ON "MBC"."DATA3" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DATA3
--------------------------------------------------------

  ALTER TABLE "MBC"."DATA3" ADD CONSTRAINT "DATA3_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MBC"."DATA3" MODIFY ("NUM" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Sequence DATA3_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MBC"."DATA3_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1020 CACHE 20 NOORDER  NOCYCLE ;
