--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HUBDATA
--------------------------------------------------------

  CREATE TABLE "MBC"."HUBDATA" 
   (	"C_ID" VARCHAR2(20 BYTE), 
	"DOMAIN" NUMBER(6,0), 
	"SOURCE" NUMBER(6,0), 
	"SOURCE_SPEC" VARCHAR2(200 BYTE), 
	"CREATION_YEAR" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"NUM" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index HUBDATA_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "MBC"."HUBDATA_PK1" ON "MBC"."HUBDATA" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table HUBDATA
--------------------------------------------------------

  ALTER TABLE "MBC"."HUBDATA" ADD CONSTRAINT "HUBDATA_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MBC"."HUBDATA" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "MBC"."HUBDATA" MODIFY ("C_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Sequence HUBDATA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MBC"."HUBDATA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11500 CACHE 20 NOORDER  NOCYCLE ;