--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HUBDATA0828
--------------------------------------------------------

  CREATE TABLE "MBC"."HUBDATA0828" 
   (	"DOC_CLASS" VARCHAR2(200 BYTE), 
	"DOC_ID" VARCHAR2(200 BYTE), 
	"CASENAMES" VARCHAR2(1000 BYTE), 
	"NORMALIZED_COURT" VARCHAR2(200 BYTE), 
	"CASETYPE" VARCHAR2(100 BYTE), 
	"ANNOUNCE_DATE" VARCHAR2(100 BYTE), 
	"SENTENCES" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SENTENCES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
